name: "off_dyna"

algo:
  _partial_: true
  _target_: cmrl.algorithms.OfflineDyna

dataset_size: 1000000
penalty_coeff: ${task.penalty_coeff}

num_envs: 8
deterministic: false
agent:
  _partial_: true
  _target_: stable_baselines3.sac.SAC
  policy: "MlpPolicy"
  env: ???
  learning_starts: 0
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  ent_coef: "auto"
  target_entropy: "auto"
  verbose: 0
  seed: ${seed}
  device: ${device}
